# Generated by Django 3.1.8 on 2021-06-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superheroes',
            old_name='catchphrase',
            new_name='catch_phrase',
        ),
    ]
